version: "3.2"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      MSSQL_AGENT_ENABLED: True
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ngeR"
    ports:
      - 1433:1433
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

networks:
  default:
    name: masstransit-stack